[en]
languageName = "ğŸ‡¬ğŸ‡§ English"
title = "Jeongseup Blog"
weight = 1

[en.params]
description = "Jeongseup's personal blog. Blockchain Protocol Specialist, DevOps, and Solution Engineer."

[ko]
languageName = "ğŸ‡°ğŸ‡· í•œêµ­ì–´"
title = "ì •ì„­ ë¸”ë¡œê·¸"
weight = 2

[ko.params]
description = "ì •ì„­ì˜ ì†Œí”„íŠ¸ì›¨ì–´ ê°œë°œ, í´ë¼ìš°ë“œ ë° ê¸°ìˆ  ë¸”ë¡œê·¸."
